CREATE TABLE COMMENT
(
	USR_NO                INTEGER NOT NULL,
	AUCTION_REG_NO        INTEGER NOT NULL,
	CMT_NO                INTEGER NULL,
	WRT_DATE              DATE NULL,
	WRT_CONT              VARCHAR(200) null,
	FOREIGN KEY R_43 (AUCTION_REG_NO) REFERENCES AUCTION(REG_NO)
	FOREIGN KEY (dept_name)
            REFERENCES department (dept_name)
)


CREATE UNIQUE INDEX XPK정보교환 ON COMMENT
(
	CMT_NO
)

ALTER TABLE COMMENT
	ADD  PRIMARY KEY (CMT_NO)
	
	
CREATE INDEX XIF1정보교환 ON COMMENT
(
	USR_NO
)


CREATE INDEX XIF2정보교환 ON COMMENT
(
	AUCTION_REG_NO
)